### ISSUE TITLE
Don’t use change-function for initialization.

### ISSUE THREAD

**Issue by rashtrakoff** [DAM-Protocol/Stroller-Protocol#17]
Location: strategies/StrategyBase.sol - General

Description:
In the StrategyBase contract, there is a changeStrollManager() function, which is seemingly also used to initialize the value of the `strollManager` variable. According to the best practice, this should be done via the constructor.

Justification:
We included this function to allow for changing `strollManager` in case we discover any bugs in `strollManager`.

Solution:
None.

**Comment by ngmachado** [comment]
Yes, I think the justification is reasonable and we should not make changes on this regard.
