### ISSUE TITLE
Use try-catch to control error message.

### ISSUE THREAD

**Issue by rashtrakoff** [DAM-Protocol/Stroller-Protocol#18]
Location: strategies/StrategyBase.sol - Line 31 - 32

Description:
In the emergencyWithdraw() function, arbitrary tokens can be transferred out of the contract in case they got stuck, etc. As errors can also occur in the ERC20 contract itself during the transfer() call, the custom TransferFailed error may not be emitted accordingly.

As an additional remark, using `safeTransfer` instead of
transfer() would make a lot of sense here, as downstream contracts use it anyways, and subsequently not using it would not save any gas cost otherwise.

Justification:
Slipped by us.

Solution:
Will implement the recommended solution of making use of a try-catch-block to ensure that the custom TransferFailed error is thrown each time a transfer failed due to any reason.

Also will use `safeTransfer` instead of a regular `transfer`.

**Comment by ngmachado** [comment]
using the safeTransfer will throw an error by itself. Don't know if makes sense to add a custom error on top. 
Using safeTransfer is already implement in another PR

**Comment by rashtrakoff** [comment]
> using the safeTransfer will throw an error by itself. Don't know if makes sense to add a custom error on top. Using safeTransfer is already implement in another PR

Yes but if we are gonna monitor the contracts for failed transfers, wouldn't `TransferFailed` custom error be easier?

**Comment by ngmachado** [comment]
don't know if is worth to add complexity at smart contract level, for something that the monitor can easily implement a solution.

**Comment by rashtrakoff** [comment]
> don't know if is worth to add complexity at smart contract level, for something that the monitor can easily implement a solution.

I don't believe it's that easy to monitor failed transactions. One will have to keep searching all the tokens/supertokens being transferred by the contract and see if a transaction has failed somewhere. Not trivial. Whereas, custom errors can be easily tracked. If you still think this isn't really a problem then we can proceed without reverting the fix for issue #16 .

**Comment by ngmachado** [comment]
The monitor in our case, only care about our own operations, all tx will go though our manager, if that reverts just check the errors. To monitor all errors, just check revert tx on manager operations.

**Comment by rashtrakoff** [comment]
> The monitor in our case, only care about our own operations, all tx will go though our manager, if that reverts just check the errors. To monitor all errors, just check revert tx on manager operations.
> 
> Maybe i'm missing something :/ but seems to be a normal operation for monitors to do.

Nah, you are right. I was thinking from the wrong perspective. Will close this.
