### ISSUE TITLE
Support partial amount top-ups.

### ISSUE THREAD

**Issue by rashtrakoff** [DAM-Protocol/Stroller-Protocol#32]
Currently, the contracts don't allow for partial amount top-ups. For example, if the supertoken amount to be topped up is worth that of 8 days of liquidity but the user only has the liquidity tokens worth 5 days of supertoken amount, the contract/strategy should still top up using all the available liquidity.

**Comment by ngmachado** [comment]
@rashtrakoff close this with last PR 🙌
